export { INSTANT_EXPLAIN_SYSTEM, getExplainPrompt } from './explain'
export { COURSE_SYSTEM, getCoursePrompt } from './course'
export { QUIZ_SYSTEM, getQuizPrompt } from './quiz'
export { DAILY_TOPIC_SYSTEM, getDailyTopicPrompt } from './daily'
export { COURSE_CHAT_SYSTEM, getCourseChatPrompt } from './course-chat'
